export {
  ProtocolClient,
  ProtocolDisconnectError,
  ProtocolRpcError,
  ProtocolTimeoutError,
  type JsonRpcErrorObject,
  type JsonRpcId,
  type NotificationHandler,
  type ServerRequestHandler,
} from "./client.ts";

export {
  classifyProtocolError,
  disconnectError,
  handlingFor,
  type ClassifiedError,
  type ErrorHandling,
  type HandshakeErrorCode,
} from "./errorModel.ts";

export {
  DEFAULT_PROTOCOL_VERSION,
  PROTOCOL_VERSION_MAX,
  PROTOCOL_VERSION_MIN,
  applyDisconnect,
  createClientTransport,
  initializeHandshake,
  isDeclaredCapability,
  isVersionInRange,
  matchProtocolVersion,
  type ClientTransport,
  type HandshakeState,
  type HandshakeStatus,
  type InitializeResult,
  type ProtocolEvent,
  type ProtocolMatch,
} from "./handshake.ts";

export type {
  ApprovalRequest,
  ApprovalResponse,
  ClientRequest,
  ErrorNotification,
  FinalAnswer,
  InitializeRequest,
  InterruptRequest,
  JobStatusUpdate,
  MessageDelta,
  PromptRequest,
  ProtocolNotification,
  QuestionRequest,
  QuestionResponse,
  RunComplete,
  ToolBegin,
  ToolEnd,
} from "./generated/types.ts";

/* Phase B: subagent protocol types */
export type {
  AgentMode,
  WorkspaceMode,
  TriggerKind,
  ChildStatus,
  PermissionVerdict,
  PermissionSpec,
  AgentDefinition,
  ContextReference,
  ContextEnvelope,
  BudgetSpec,
  WorkspaceScope,
  TaskRequest,
  UsageRecord,
  ErrorRecord,
  ArtifactRef,
  EvidenceRef,
  TaskResult,
  ChildSessionEvent,
  AgentInvokeRequest,
  TaskStartRequest,
} from "./generated/subagent-types.ts";