"""Phase B · Isolated Subagent Runtime.

Public facade exports:
  - AgentDefinition, TaskRequest, TaskResult (from protocol)
  - AgentDefinitionRegistry, load_agent_definitions (from definitions)
  - ChildRuntime (from runtime, when B5 is implemented)
"""

from protocol.subagents import (
    AgentDefinition,
    AgentMode,
    BudgetSpec,
    ChildStatus,
    ContextEnvelope,
    ContextReference,
    EffectiveTaskPolicy,
    ErrorRecord,
    EvidenceRef,
    PermissionRule,
    PermissionSpec,
    PermissionVerdict,
    TaskPermissionSpec,
    TaskRequest,
    TaskResult,
    ToolPermission,
    TriggerKind,
    UsageRecord,
    WorkspaceMode,
    WorkspaceScope,
)

from .definitions import (
    AgentDefinitionRegistry,
    DefinitionError,
    load_agent_definitions,
    validate_agent_definition,
)
from .modes import (
    SessionIdentity,
    SessionMode,
    SubagentCapability,
    SubagentConfig,
    SubagentFeatureFlags,
    build_capability,
    get_subagent_config,
    reset_subagent_config,
    set_subagent_config,
    validate_primary_entry,
    validate_subagent_entry,
)
from .sessions import (
    ChildSession,
    InvalidStateTransition,
    SessionNotFound,
    SessionTree,
    create_child_session,
    transition,
)
from .runtime import (
    AgentRuntime,
    AuditScope,
    BudgetExceededError,
    BudgetGuard,
    CancellationToken,
    ChildCancelledError,
    ChildRuntime,
    NamespaceIsolator,
    ScopedToolRegistry,
    create_child_runtime,
    create_runtime,
)
from .context import (
    ContextBuilder,
    ContextValidationError,
    ReferenceValidationError,
    create_minimal_context,
    is_field_redacted,
    redact_text,
)
from .manager import (
    AgentNotFoundError,
    ChildSessionManager,
    DepthLimitExceededError,
    DispatchError,
    FeatureDisabledError,
    ModeMismatchError,
    TaskPermissionDeniedError,
)
from .registry_provider import (
    get_manager,
    get_manager_or_none,
    init_manager,
    reset_manager,
)
from .permissions import (
    ApprovalDecision,
    ApprovalManager,
    ApprovalRequest,
    DecisionKind,
    PermissionDecision,
    PermissionPolicy,
    is_system_hard_denied,
)
from .workspace import (
    Lease,
    LeaseConflictError,
    LeaseExpiredError,
    LeaseManager,
    NoWorkspaceScopeError,
    OutsidePathError,
    WorkspaceError,
    WorkspaceValidator,
    is_read_only_command,
    make_validator,
)
from .budget import (
    BudgetError,
    CancellationScope,
    ConcurrencyGuard,
    ConcurrencyLimitExceeded,
    StepLimitExceeded,
    TimeLimitExceeded,
    TokenLimitExceeded,
    TotalTaskLimitExceeded,
    terminate_for_budget_error,
)

__all__ = [
    # Protocol types
    "AgentDefinition",
    "AgentMode",
    "BudgetSpec",
    "ChildStatus",
    "ContextEnvelope",
    "ContextReference",
    "EffectiveTaskPolicy",
    "ErrorRecord",
    "EvidenceRef",
    "PermissionRule",
    "PermissionSpec",
    "PermissionVerdict",
    "TaskPermissionSpec",
    "TaskRequest",
    "TaskResult",
    "ToolPermission",
    "TriggerKind",
    "UsageRecord",
    "WorkspaceMode",
    "WorkspaceScope",
    # Registry
    "AgentDefinitionRegistry",
    "DefinitionError",
    "load_agent_definitions",
    "validate_agent_definition",
    # Modes & config
    "SessionIdentity",
    "SessionMode",
    "SubagentCapability",
    "SubagentConfig",
    "SubagentFeatureFlags",
    "build_capability",
    "get_subagent_config",
    "reset_subagent_config",
    "set_subagent_config",
    "validate_primary_entry",
    "validate_subagent_entry",
    # Sessions
    "ChildSession",
    "InvalidStateTransition",
    "SessionNotFound",
    "SessionTree",
    "create_child_session",
    "transition",
    # Runtime
    "AgentRuntime",
    "AuditScope",
    "BudgetExceededError",
    "BudgetGuard",
    "CancellationToken",
    "ChildCancelledError",
    "ChildRuntime",
    "NamespaceIsolator",
    "ScopedToolRegistry",
    "create_child_runtime",
    "create_runtime",
    # Context
    "ContextBuilder",
    "ContextValidationError",
    "ReferenceValidationError",
    "create_minimal_context",
    "is_field_redacted",
    "redact_text",
    # Manager
    "AgentNotFoundError",
    "ChildSessionManager",
    "DepthLimitExceededError",
    "DispatchError",
    "FeatureDisabledError",
    "ModeMismatchError",
    "TaskPermissionDeniedError",
    # Registry provider
    "get_manager",
    "get_manager_or_none",
    "init_manager",
    "reset_manager",
    # Permissions
    "ApprovalDecision",
    "ApprovalManager",
    "ApprovalRequest",
    "DecisionKind",
    "PermissionDecision",
    "PermissionPolicy",
    "is_system_hard_denied",
    # Workspace
    "Lease",
    "LeaseConflictError",
    "LeaseExpiredError",
    "LeaseManager",
    "NoWorkspaceScopeError",
    "OutsidePathError",
    "WorkspaceError",
    "WorkspaceValidator",
    "is_read_only_command",
    "make_validator",
    # Budget
    "BudgetError",
    "CancellationScope",
    "ConcurrencyGuard",
    "ConcurrencyLimitExceeded",
    "StepLimitExceeded",
    "TimeLimitExceeded",
    "TokenLimitExceeded",
    "TotalTaskLimitExceeded",
    "terminate_for_budget_error",
]
