import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'
import { CHEVRON_GAP_PX, chevron, HOVER_DARK, HOVER_LIGHT, projectCategories } from '../../../lib/sessionCategories.ts'
import { sessionVisualState } from './sessionVisualState.ts'

const css = readFileSync(join(dirname(fileURLToPath(import.meta.url)), '../assets/main.css'), 'utf8')

test('H15 five-state mapping covers empty/loading/error/narrow/dark', () => {
  assert.equal(sessionVisualState({ loading: true, error: null, empty: true, narrow: false, dark: true }), 'loading')
  assert.equal(sessionVisualState({ loading: false, error: 'x', empty: false, narrow: false, dark: true }), 'error')
  assert.equal(sessionVisualState({ loading: false, error: null, empty: true, narrow: false, dark: true }), 'empty')
  assert.equal(sessionVisualState({ loading: false, error: null, empty: false, narrow: true, dark: true }), 'narrow')
  assert.equal(sessionVisualState({ loading: false, error: null, empty: false, narrow: false, dark: true }), 'dark')
  assert.equal(sessionVisualState({ loading: false, error: null, empty: false, narrow: false, dark: false }), 'ok')
})

test('sidebar pins settings, adds project folders, and uses a dark theme menu', () => {
  const src = readFileSync(join(dirname(fileURLToPath(import.meta.url)), 'SessionList.tsx'), 'utf8')
  const composer = readFileSync(join(dirname(fileURLToPath(import.meta.url)), 'Composer.tsx'), 'utf8')
  const chat = readFileSync(join(dirname(fileURLToPath(import.meta.url)), 'ChatArea.tsx'), 'utf8')
  assert.match(src, /data-testid="add-project"/)
  assert.match(src, /data-testid="new-in-recent"/)
  assert.match(src, /data-testid=\{`new-in-project-\$\{/)
  assert.match(src, /session-scroll/)
  assert.match(src, /onAddProject/)
  assert.match(src, /onCreateInProject/)
  assert.doesNotMatch(src, /className="session-id"/)
  assert.doesNotMatch(src, /data-testid="session-recycle"/)
  assert.match(src, /data-testid=\{`pin-task-\$\{/)
  assert.match(src, /onPin/)
  assert.match(src, /session-actions/)
  assert.match(src, /onContextMenu/)
  assert.match(src, /SessionContextMenu/)
  assert.doesNotMatch(src, /Pencil/)
  assert.match(css, /\.session-actions \{[\s\S]*opacity:\s*0/)
  assert.match(css, /\.session-row:hover \.session-actions/)
  assert.doesNotMatch(css, /\.session-row:focus-within \.session-actions/)
  assert.match(css, /\.session-ctx \{/)
  assert.match(src, /session-unread-dot/)
  assert.match(src, /session-project-folder/)
  assert.match(src, /session-list-in-project/)
  assert.match(src, /ProjectContextMenu/)
  assert.match(src, /project-more-/)
  assert.match(src, /session-project-actions/)
  assert.match(css, /\.session-project-actions \{[\s\S]*opacity:\s*0/)
  assert.match(css, /\.session-project-head:hover \.session-project-actions/)
  assert.doesNotMatch(css, /\.session-project-head:focus-within \.session-project-actions/)
  assert.match(css, /\.panel-header \.new-session \{[\s\S]*opacity:\s*0/)
  assert.match(css, /\.panel-header:hover \.new-session/)
  assert.match(css, /\.session-category-head \.session-head-action \{[\s\S]*opacity:\s*0/)
  assert.match(css, /\.session-category-head:hover \.session-head-action/)
  assert.doesNotMatch(css, /\.session-category-head:focus-within \.session-head-action/)
  assert.match(src, /TitleMarquee/)
  assert.match(src, /sharedMarqueePxPerSec/)
  assert.match(src, /pxPerSec=\{titlePxPerSec\}/)
  assert.match(css, /\.session-row:hover \.title-marquee\.is-overflow \.title-marquee-track/)
  assert.doesNotMatch(css, /\.session-row:focus-within \.title-marquee\.is-overflow \.title-marquee-track/)
  assert.match(css, /\.session-actions \{[\s\S]*position:\s*static/)
  assert.match(src, /data-testid="sidebar-scheduled"/)
  assert.match(src, /data-testid="sidebar-plugins"/)
  assert.match(src, /visibleProjectSessions/)
  assert.match(src, /expandShow/)
  assert.match(src, /session-project-expand/)
  assert.match(css, /\.session-project-expand/)
  assert.doesNotMatch(css, /\.composer-send:hover:not\(:disabled\)\s*\{\s*background:\s*var\(--cc-accent\)/)
  assert.doesNotMatch(css, /\.composer-stop\s*\{\s*background:\s*var\(--cc-danger\)/)
  assert.match(composer, /showProjectChip/)
  assert.match(css, /\.archived-chats/)
  assert.match(css, /\.pin-button\.is-pinned/)
  assert.match(css, /\.session-row:hover \.session-actions/)
  assert.match(css, /\.session-item\.active\s*\{[\s\S]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.1/)
  assert.match(src, /chrome === 'spin' \? ' is-running'/)
  assert.match(src, /className="session-title-row"[\s\S]*StatusIndicator[\s\S]*TitleMarquee/)
  assert.doesNotMatch(src, /className="session-title-row"[\s\S]*TitleMarquee[\s\S]*StatusIndicator/)
  assert.match(css, /\.session-row\.is-running/)
  assert.match(css, /\.status-indicator\[data-status='spin'\][\s\S]*#d0d7de|#8b949e|rgba\(255,\s*255,\s*255/)
  assert.match(css, /\.session-list-in-project \.session-row\s*\{[\s\S]*padding-left:\s*30px/)
  assert.match(css, /\.session-list-in-project \.session-item\s*\{[\s\S]*padding-left:\s*0/)
  assert.match(css, /@keyframes title-marquee-scroll/)
  assert.match(composer, /ThemeMenu/)
  assert.match(composer, /PermissionMenu/)
  assert.match(composer, /testId="composer-permission-mode"/)
  assert.match(composer, /testId="composer-model"/)
  assert.match(chat, /emptyChatGreeting/)
  assert.match(chat, /chat-team-lane/)
  assert.match(css, /\.session-scroll\s*\{/)
  assert.match(css, /\.theme-menu-panel\s*\{/)
  assert.match(css, /\.settings-page\s*\{[\s\S]*width:\s*1040px/)
  assert.match(css, /\.settings-page\s*\{[\s\S]*height:\s*720px/)
})

test('H15 three categories, chevron, recycle BLOCKED, hover sample in CSS', () => {
  const buckets = projectCategories(
    [
      { sessionId: 'p', title: 'a', workspaceRoot: '', pinned: true },
      { sessionId: 'proj', title: 'b', workspaceRoot: 'D:\\work', projectId: 'D:\\work' },
      { sessionId: 'r', title: 'c', workspaceRoot: '' }
    ],
    false
  )
  assert.equal(buckets.pinned[0]?.sessionId, 'p')
  assert.equal(buckets.projects['D:\\work']?.[0]?.sessionId, 'proj')
  assert.equal(buckets.recent[0]?.sessionId, 'r')
  assert.equal(buckets.recycleBlocked, true)
  assert.equal(chevron(true), 'v')
  assert.equal(chevron(false), '>')
  assert.equal(CHEVRON_GAP_PX, 4)
  assert.equal(HOVER_LIGHT, 'rgba(0,0,0,0.06)')
  assert.equal(HOVER_DARK, 'rgba(255,255,255,0.08)')
  assert.match(css, /rgba\(255,\s*255,\s*255,\s*0\.08\)/)
  assert.match(css, /rgba\(0,\s*0,\s*0,\s*0\.06\)/)
  assert.match(css, /margin-left:\s*4px/)
  assert.match(css, /session-panel\[data-visual-state='narrow'\]/)
})
